/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UnicodeLetter = 5;
  /** RegularExpression Id. */
  int UnicodeDigit = 6;
  /** RegularExpression Id. */
  int IdentifierStart = 7;
  /** RegularExpression Id. */
  int IdentifierPart = 8;
  /** RegularExpression Id. */
  int IdentifierName = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<UnicodeLetter>",
    "<UnicodeDigit>",
    "<IdentifierStart>",
    "<IdentifierPart>",
    "<IdentifierName>",
  };

}
